package io.github.pylonmc.pylon;

import io.github.pylonmc.pylon.content.assembling.AssemblyTable;
import io.github.pylonmc.pylon.content.blocks.SleepingBag;
import io.github.pylonmc.pylon.content.building.*;
import io.github.pylonmc.pylon.content.components.*;
import io.github.pylonmc.pylon.content.machines.cargo.*;
import io.github.pylonmc.pylon.content.machines.diesel.machines.*;
import io.github.pylonmc.pylon.content.machines.diesel.production.Biorefinery;
import io.github.pylonmc.pylon.content.machines.diesel.production.Fermenter;
import io.github.pylonmc.pylon.content.machines.experience.FluidExperienceBottler;
import io.github.pylonmc.pylon.content.machines.experience.ExperienceDrain;
import io.github.pylonmc.pylon.content.machines.experience.ExperienceFountain;
import io.github.pylonmc.pylon.content.machines.fluid.*;
import io.github.pylonmc.pylon.content.machines.hydraulics.*;
import io.github.pylonmc.pylon.content.machines.simple.*;
import io.github.pylonmc.pylon.content.machines.smelting.*;
import io.github.pylonmc.pylon.content.machines.storage.Silo;
import io.github.pylonmc.pylon.content.machines.storage.SiloConverter;
import io.github.pylonmc.pylon.content.resources.RefractoryMix;
import io.github.pylonmc.rebar.block.RebarBlock;
import io.github.pylonmc.rebar.content.cargo.CargoDuct;
import org.bukkit.Material;


public final class PylonBlocks {

    private PylonBlocks() {
        throw new AssertionError("Utility class");
    }

    public static void initialize() {
        RebarBlock.register(PylonKeys.RAW_TIN_BLOCK, Material.RAW_IRON_BLOCK, RebarBlock.class);
        RebarBlock.register(PylonKeys.TIN_BLOCK, Material.IRON_BLOCK, RebarBlock.class);
        RebarBlock.register(PylonKeys.BRONZE_BLOCK, Material.COPPER_BLOCK, RebarBlock.class);
        RebarBlock.register(PylonKeys.STEEL_BLOCK, Material.NETHERITE_BLOCK, RebarBlock.class);
        RebarBlock.register(PylonKeys.PALLADIUM_BLOCK, Material.IRON_BLOCK, RebarBlock.class);
        RebarBlock.register(PylonKeys.CHARCOAL_BLOCK, Material.COAL_BLOCK, RebarBlock.class);
        RebarBlock.register(PylonKeys.SULFUR_BLOCK, Material.YELLOW_TERRACOTTA, RebarBlock.class);
        RebarBlock.register(PylonKeys.GYPSUM_BLOCK, Material.QUARTZ_BLOCK, RebarBlock.class);
        RebarBlock.register(PylonKeys.SPRINKLER, Material.FLOWER_POT, Sprinkler.class);
        RebarBlock.register(PylonKeys.SHIMMER_PEDESTAL, Material.MOSSY_STONE_BRICK_WALL, Pedestal.class);
        RebarBlock.register(PylonKeys.PEDESTAL, Material.STONE_BRICK_WALL, Pedestal.class);
        RebarBlock.register(PylonKeys.SHIMMER_ALTAR, Material.SMOOTH_STONE_SLAB, ShimmerAltar.class);
        RebarBlock.register(PylonKeys.GRINDSTONE, Material.SMOOTH_STONE_SLAB, Grindstone.class);
        RebarBlock.register(PylonKeys.GRINDSTONE_HANDLE, Material.OAK_FENCE, GrindstoneHandle.class);
        RebarBlock.register(PylonKeys.ENRICHED_SOUL_SOIL, Material.SOUL_SOIL, RebarBlock.class);
        RebarBlock.register(PylonKeys.MIXING_POT, Material.CAULDRON, MixingPot.class);
        RebarBlock.register(PylonKeys.PIPED_CAULDRON, Material.CAULDRON, PipedCauldron.class);
        RebarBlock.register(PylonKeys.CRUCIBLE, Material.CAULDRON, Crucible.class);
        RebarBlock.register(PylonKeys.IGNEOUS_COMPOSITE, Material.OBSIDIAN, WitherProofBlock.class);
        RebarBlock.register(PylonKeys.PORTABLE_FLUID_TANK_WOOD, Material.BROWN_STAINED_GLASS, PortableFluidTank.class);
        RebarBlock.register(PylonKeys.PORTABLE_FLUID_TANK_COPPER, Material.ORANGE_STAINED_GLASS, PortableFluidTank.class);
        RebarBlock.register(PylonKeys.PORTABLE_FLUID_TANK_TIN, Material.GREEN_STAINED_GLASS, PortableFluidTank.class);
        RebarBlock.register(PylonKeys.PORTABLE_FLUID_TANK_IRON, Material.LIGHT_GRAY_STAINED_GLASS, PortableFluidTank.class);
        RebarBlock.register(PylonKeys.PORTABLE_FLUID_TANK_BRONZE, Material.ORANGE_STAINED_GLASS, PortableFluidTank.class);
        RebarBlock.register(PylonKeys.PORTABLE_FLUID_TANK_OBSIDIAN, Material.BLACK_STAINED_GLASS, PortableFluidTank.class);
        RebarBlock.register(PylonKeys.PORTABLE_FLUID_TANK_IGNEOUS_COMPOSITE, Material.BLACK_STAINED_GLASS, PortableFluidTank.class);
        RebarBlock.register(PylonKeys.PORTABLE_FLUID_TANK_STEEL, Material.GRAY_STAINED_GLASS, PortableFluidTank.class);
        RebarBlock.register(PylonKeys.PORTABLE_FLUID_TANK_PALLADIUM, Material.BLUE_STAINED_GLASS, PortableFluidTank.class);
        RebarBlock.register(PylonKeys.FLUID_TANK, Material.GRAY_TERRACOTTA, FluidTank.class);
        RebarBlock.register(PylonKeys.FLUID_TANK_CASING_WOOD, Material.BROWN_STAINED_GLASS, FluidTankCasing.class);
        RebarBlock.register(PylonKeys.FLUID_TANK_CASING_COPPER, Material.ORANGE_STAINED_GLASS, FluidTankCasing.class);
        RebarBlock.register(PylonKeys.FLUID_TANK_CASING_TIN, Material.GREEN_STAINED_GLASS, FluidTankCasing.class);
        RebarBlock.register(PylonKeys.FLUID_TANK_CASING_IRON, Material.LIGHT_GRAY_STAINED_GLASS, FluidTankCasing.class);
        RebarBlock.register(PylonKeys.FLUID_TANK_CASING_BRONZE, Material.ORANGE_STAINED_GLASS, FluidTankCasing.class);
        RebarBlock.register(PylonKeys.FLUID_TANK_CASING_OBSIDIAN, Material.BLACK_STAINED_GLASS, FluidTankCasing.class);
        RebarBlock.register(PylonKeys.FLUID_TANK_CASING_IGNEOUS_COMPOSITE, Material.BLACK_STAINED_GLASS, FluidTankCasing.class);
        RebarBlock.register(PylonKeys.FLUID_TANK_CASING_STEEL, Material.GRAY_STAINED_GLASS, FluidTankCasing.class);
        RebarBlock.register(PylonKeys.FLUID_TANK_CASING_PALLADIUM, Material.BLUE_STAINED_GLASS, FluidTankCasing.class);
        RebarBlock.register(PylonKeys.FLUID_INPUT_HATCH, Material.LIGHT_BLUE_TERRACOTTA, FluidInputHatch.class);
        RebarBlock.register(PylonKeys.FLUID_OUTPUT_HATCH, Material.ORANGE_TERRACOTTA, FluidOutputHatch.class);
        RebarBlock.register(PylonKeys.ITEM_INPUT_HATCH, Material.GREEN_TERRACOTTA, ItemInputHatch.class);
        RebarBlock.register(PylonKeys.ITEM_OUTPUT_HATCH, Material.RED_TERRACOTTA, ItemOutputHatch.class);
        RebarBlock.register(PylonKeys.FLUID_VALVE, Material.STRUCTURE_VOID, FluidValve.class);
        RebarBlock.register(PylonKeys.WATER_PUMP, Material.BLUE_TERRACOTTA, WaterPump.class);
        RebarBlock.register(PylonKeys.FLUID_FILTER, Material.STRUCTURE_VOID, FluidFilter.class);
        RebarBlock.register(PylonKeys.FLUID_LIMITER, Material.STRUCTURE_VOID, FluidLimiter.class);
        RebarBlock.register(PylonKeys.FLUID_ACCUMULATOR, Material.STRUCTURE_VOID, FluidAccumulator.class);
        RebarBlock.register(PylonKeys.FLUID_METER, Material.STRUCTURE_VOID, FluidMeter.class);
        RebarBlock.register(PylonKeys.WATER_PLACER, Material.DISPENSER, FluidPlacer.class);
        RebarBlock.register(PylonKeys.LAVA_PLACER, Material.DISPENSER, FluidPlacer.class);
        RebarBlock.register(PylonKeys.WATER_DRAINER, Material.DISPENSER, FluidDrainer.class);
        RebarBlock.register(PylonKeys.LAVA_DRAINER, Material.DISPENSER, FluidDrainer.class);
        RebarBlock.register(PylonKeys.FLUID_VOIDER_1, Material.STRUCTURE_VOID, FluidVoider.class);
        RebarBlock.register(PylonKeys.FLUID_VOIDER_2, Material.STRUCTURE_VOID, FluidVoider.class);
        RebarBlock.register(PylonKeys.CREATIVE_FLUID_VOIDER, Material.STRUCTURE_VOID, FluidVoider.class);
        RebarBlock.register(PylonKeys.CREATIVE_FLUID_SOURCE, Material.PINK_CONCRETE, CreativeFluidSource.class);
        RebarBlock.register(PylonKeys.REFRACTORY_MIX, Material.SMOOTH_RED_SANDSTONE, RefractoryMix.class);
        RebarBlock.register(PylonKeys.REFRACTORY_BRICKS, Material.DEEPSLATE_TILES, SmelteryComponent.class);
        RebarBlock.register(PylonKeys.BLOOMERY, Material.MAGMA_BLOCK, Bloomery.class);
        RebarBlock.register(PylonKeys.BRONZE_ANVIL, Material.ANVIL, BronzeAnvil.class);
        RebarBlock.register(PylonKeys.SMELTERY_CONTROLLER, Material.BLAST_FURNACE, SmelteryController.class);
        RebarBlock.register(PylonKeys.SMELTERY_INPUT_HATCH, Material.LIGHT_BLUE_TERRACOTTA, SmelteryInputHatch.class);
        RebarBlock.register(PylonKeys.SMELTERY_OUTPUT_HATCH, Material.ORANGE_TERRACOTTA, SmelteryOutputHatch.class);
        RebarBlock.register(PylonKeys.SMELTERY_HOPPER, Material.HOPPER, SmelteryHopper.class);
        RebarBlock.register(PylonKeys.SMELTERY_BURNER, Material.FURNACE, SmelteryBurner.class);
        RebarBlock.register(PylonKeys.DIESEL_SMELTERY_HEATER, Material.FURNACE, DieselSmelteryHeater.class);
        RebarBlock.register(PylonKeys.CASTING_UNIT, Material.BRICKS, CastingUnit.class);
        RebarBlock.register(PylonKeys.FORMING_TABLE, Material.CRAFTING_TABLE, FormingTable.class);
        RebarBlock.register(PylonKeys.FLUID_STRAINER, Material.COPPER_GRATE, FluidStrainer.class);
        RebarBlock.register(PylonKeys.EXPLOSIVE_TARGET, Material.TARGET, ExplosiveTarget.class);
        RebarBlock.register(PylonKeys.EXPLOSIVE_TARGET_FIERY, Material.TARGET, ExplosiveTarget.class);
        RebarBlock.register(PylonKeys.EXPLOSIVE_TARGET_SUPER, Material.TARGET, ExplosiveTarget.class);
        RebarBlock.register(PylonKeys.EXPLOSIVE_TARGET_SUPER_FIERY, Material.TARGET, ExplosiveTarget.class);
        RebarBlock.register(PylonKeys.IMMOBILIZER, Material.PISTON, Immobilizer.class);
        RebarBlock.register(PylonKeys.ELEVATOR_1, Material.SMOOTH_QUARTZ_SLAB, Elevator.class);
        RebarBlock.register(PylonKeys.ELEVATOR_2, Material.SMOOTH_QUARTZ_SLAB, Elevator.class);
        RebarBlock.register(PylonKeys.ELEVATOR_3, Material.SMOOTH_QUARTZ_SLAB, Elevator.class);
        RebarBlock.register(PylonKeys.PRESS, Material.COMPOSTER, Press.class);
        RebarBlock.register(PylonKeys.HYDRAULIC_GRINDSTONE_TURNER, Material.SMOOTH_STONE, HydraulicGrindstoneTurner.class);
        RebarBlock.register(PylonKeys.HYDRAULIC_MIXING_ATTACHMENT, Material.CHISELED_STONE_BRICKS, HydraulicMixingAttachment.class);
        RebarBlock.register(PylonKeys.HYDRAULIC_PRESS_PISTON, Material.BROWN_TERRACOTTA, HydraulicPressPiston.class);
        RebarBlock.register(PylonKeys.HYDRAULIC_HAMMER_HEAD, Material.STONE_BRICKS, HydraulicHammerHead.class);
        RebarBlock.register(PylonKeys.HYDRAULIC_PIPE_BENDER, Material.WAXED_CHISELED_COPPER, HydraulicPipeBender.class);
        RebarBlock.register(PylonKeys.HYDRAULIC_TABLE_SAW, Material.WAXED_CUT_COPPER, HydraulicTableSaw.class);
        RebarBlock.register(PylonKeys.SOLAR_LENS, Material.GLASS_PANE, SolarLens.class);
        RebarBlock.register(PylonKeys.MANUAL_HYDRAULIC_PURIFIER, Material.DECORATED_POT, ManualHydraulicPurifier.class);
        RebarBlock.register(PylonKeys.COPPER_FRAMED_GLASS, Material.ORANGE_STAINED_GLASS, RebarBlock.class);
        RebarBlock.register(PylonKeys.QUARTZ_CAP, Material.QUARTZ_SLAB, RebarBlock.class);
        RebarBlock.register(PylonKeys.SOLAR_HYDRAULIC_PURIFIER_1, Material.WAXED_COPPER_BLOCK, SolarHydraulicPurifier.class);
        RebarBlock.register(PylonKeys.SOLAR_HYDRAULIC_PURIFIER_2, Material.WAXED_COPPER_BLOCK, SolarHydraulicPurifier.class);
        RebarBlock.register(PylonKeys.SOLAR_HYDRAULIC_PURIFIER_3, Material.WAXED_COPPER_BLOCK, SolarHydraulicPurifier.class);
        RebarBlock.register(PylonKeys.SOLAR_HYDRAULIC_PURIFIER_4, Material.WAXED_COPPER_BLOCK, SolarHydraulicPurifier.class);
        RebarBlock.register(PylonKeys.SOLAR_HYDRAULIC_PURIFIER_5, Material.WAXED_COPPER_BLOCK, SolarHydraulicPurifier.class);
        RebarBlock.register(PylonKeys.BURNER_HYDRAULIC_PURIFIER, Material.BLAST_FURNACE, BurnerHydraulicPurifier.class);
        RebarBlock.register(PylonKeys.CONVECTION_HYDRAULIC_PURIFIER, Material.SMOOTH_STONE, ConvectionHydraulicPurifier.class);
        RebarBlock.register(PylonKeys.LISELETTE_HYDRAULIC_PURIFIER, Material.OCHRE_FROGLIGHT, LiseletteHydraulicPurifier.class);
        RebarBlock.register(PylonKeys.MANUAL_CORE_DRILL_LEVER, Material.LEVER, ManualCoreDrillLever.class);
        RebarBlock.register(PylonKeys.MANUAL_CORE_DRILL, Material.CHISELED_STONE_BRICKS, ManualCoreDrill.class);
        RebarBlock.register(PylonKeys.IMPROVED_MANUAL_CORE_DRILL, Material.WAXED_OXIDIZED_COPPER, ImprovedManualCoreDrill.class);
        RebarBlock.register(PylonKeys.HYDRAULIC_CORE_DRILL, Material.WAXED_COPPER_BULB, HydraulicCoreDrill.class);
        RebarBlock.register(PylonKeys.DIESEL_CORE_DRILL, Material.IRON_BLOCK, DieselCoreDrill.class);
        RebarBlock.register(PylonKeys.PALLADIUM_CONDENSER, Material.NETHERITE_BLOCK, PalladiumCondenser.class);
        RebarBlock.register(PylonKeys.VACUUM_HOPPER_1, Material.HOPPER, VacuumHopper.class);
        RebarBlock.register(PylonKeys.VACUUM_HOPPER_2, Material.HOPPER, VacuumHopper.class);
        RebarBlock.register(PylonKeys.VACUUM_HOPPER_3, Material.HOPPER, VacuumHopper.class);
        RebarBlock.register(PylonKeys.VACUUM_HOPPER_4, Material.HOPPER, VacuumHopper.class);
        RebarBlock.register(PylonKeys.HYDRAULIC_REFUELING_STATION, Material.WAXED_CUT_COPPER_SLAB, HydraulicRefuelingStation.class);
        RebarBlock.register(PylonKeys.HYDRAULIC_FARMER, Material.WAXED_EXPOSED_COPPER_BULB, HydraulicFarmer.class);
        RebarBlock.register(PylonKeys.HYDRAULIC_BREAKER, Material.WAXED_EXPOSED_CUT_COPPER, HydraulicBreaker.class);
        RebarBlock.register(PylonKeys.DIESEL_PIPE_BENDER, Material.IRON_BLOCK, DieselPipeBender.class);
        RebarBlock.register(PylonKeys.DIESEL_TABLE_SAW, Material.IRON_BLOCK, DieselTableSaw.class);
        RebarBlock.register(PylonKeys.DIESEL_PRESS, Material.IRON_BLOCK, DieselPress.class);
        RebarBlock.register(PylonKeys.DIESEL_GRINDSTONE, Material.IRON_BLOCK, DieselGrindstone.class);
        RebarBlock.register(PylonKeys.DIESEL_BRICK_MOLDER, Material.IRON_BLOCK, DieselBrickMolder.class);
        RebarBlock.register(PylonKeys.DIESEL_HAMMER_HEAD, Material.IRON_BLOCK, DieselHammerHead.class);
        RebarBlock.register(PylonKeys.DIESEL_MIXING_ATTACHMENT, Material.IRON_BLOCK, DieselMixingAttachment.class);
        RebarBlock.register(PylonKeys.DIESEL_FURNACE, Material.FURNACE, DieselFurnace.class);
        RebarBlock.register(PylonKeys.DIESEL_BREAKER, Material.DROPPER, DieselBreaker.class);
        RebarBlock.register(PylonKeys.DIESEL_QUARRY, Material.IRON_BLOCK, DieselQuarry.class);
        RebarBlock.register(PylonKeys.DIESEL_REFUELING_STATION, Material.QUARTZ_SLAB, DieselRefuelingStation.class);
        RebarBlock.register(PylonKeys.FERMENTER, Material.PINK_TERRACOTTA, Fermenter.class);
        RebarBlock.register(PylonKeys.REINFORCED_GLASS, Material.GRAY_STAINED_GLASS, RebarBlock.class);
        RebarBlock.register(PylonKeys.REINFORCED_GLASS_CASING, Material.GRAY_STAINED_GLASS_PANE, ReinforcedGlassCasing.class);
        RebarBlock.register(PylonKeys.BIOREFINERY, Material.PURPLE_TERRACOTTA, Biorefinery.class);
        RebarBlock.register(PylonKeys.BRONZE_FOUNDATION, Material.LIGHT_GRAY_CONCRETE, RebarBlock.class);
        RebarBlock.register(PylonKeys.BRONZE_GRATING, Material.WAXED_COPPER_BARS, RebarBlock.class);
        RebarBlock.register(PylonKeys.IRON_SUPPORT_BEAM, Material.POLISHED_DEEPSLATE_WALL, RebarBlock.class);
        RebarBlock.register(PylonKeys.STEEL_SUPPORT_BEAM, Material.POLISHED_TUFF_WALL, RebarBlock.class);
        RebarBlock.register(PylonKeys.REINFORCED_PLATING, Material.GRAY_STAINED_GLASS_PANE, RebarBlock.class);
        RebarBlock.register(PylonKeys.DISTILLATION_TOWER_RING, Material.IRON_BLOCK, RebarBlock.class);
        RebarBlock.register(PylonKeys.SMOKESTACK_RING, Material.BRICK_WALL, RebarBlock.class);
        RebarBlock.register(PylonKeys.SMOKESTACK_CAP, Material.FLOWER_POT, SmokestackCap.class);
        RebarBlock.register(PylonKeys.CARGO_DUCT, Material.STRUCTURE_VOID, CargoDuct.class);
        RebarBlock.register(PylonKeys.CARGO_BUFFER, Material.STRUCTURE_VOID, CargoBuffer.class);
        RebarBlock.register(PylonKeys.CARGO_EXTRACTOR, Material.STRUCTURE_VOID, CargoExtractor.class);
        RebarBlock.register(PylonKeys.CARGO_INSERTER, Material.STRUCTURE_VOID, CargoInserter.class);
        RebarBlock.register(PylonKeys.CARGO_SPLITTER, Material.STRUCTURE_VOID, CargoSplitter.class);
        RebarBlock.register(PylonKeys.CARGO_MERGER, Material.STRUCTURE_VOID, CargoMerger.class);
        RebarBlock.register(PylonKeys.CARGO_VALVE, Material.STRUCTURE_VOID, CargoValve.class);
        RebarBlock.register(PylonKeys.CARGO_FILTER, Material.STRUCTURE_VOID, CargoFilter.class);
        RebarBlock.register(PylonKeys.CARGO_MONITOR, Material.STRUCTURE_VOID, CargoMonitor.class);
        RebarBlock.register(PylonKeys.CARGO_METER, Material.STRUCTURE_VOID, CargoMeter.class);
        RebarBlock.register(PylonKeys.CARGO_GATE, Material.STRUCTURE_VOID, CargoGate.class);
        RebarBlock.register(PylonKeys.CARGO_ACCUMULATOR, Material.STRUCTURE_VOID, CargoAccumulator.class);
        RebarBlock.register(PylonKeys.CARGO_FLUID_ACCUMULATOR, Material.STRUCTURE_VOID, CargoFluidAccumulator.class);
        RebarBlock.register(PylonKeys.CARGO_OVERFLOW_GATE, Material.STRUCTURE_VOID, CargoOverflowGate.class);
        RebarBlock.register(PylonKeys.ASSEMBLY_TABLE, Material.ANVIL, AssemblyTable.class);
        RebarBlock.register(PylonKeys.CREATIVE_ITEM_SOURCE, Material.STRUCTURE_VOID, CreativeItemSource.class);
        RebarBlock.register(PylonKeys.CREATIVE_ITEM_VOIDER, Material.STRUCTURE_VOID, CreativeItemVoider.class);
        RebarBlock.register(PylonKeys.POTION_PEDESTAL, Material.END_STONE_BRICK_WALL, PotionPedestal.class);
        RebarBlock.register(PylonKeys.POTION_ALTAR, Material.STONE_BRICK_SLAB, PotionAltar.class);
        RebarBlock.register(PylonKeys.COLLIMATOR, Material.OBSIDIAN, Collimator.class);
        RebarBlock.register(PylonKeys.COLLIMATOR_PILLAR, Material.DEEPSLATE_TILE_WALL, CollimatorPillar.class);
        RebarBlock.register(PylonKeys.CRUDE_ALLOY_FURNACE, Material.BLAST_FURNACE, CrudeAlloyFurnace.class);
        RebarBlock.register(PylonKeys.KILN, Material.BLAST_FURNACE, Kiln.class);
        RebarBlock.register(PylonKeys.WOODEN_SILO, Material.BROWN_TERRACOTTA, Silo.class);
        RebarBlock.register(PylonKeys.COPPER_SILO, Material.TERRACOTTA, Silo.class);
        RebarBlock.register(PylonKeys.TIN_SILO, Material.GREEN_TERRACOTTA, Silo.class);
        RebarBlock.register(PylonKeys.IRON_SILO, Material.LIGHT_GRAY_TERRACOTTA, Silo.class);
        RebarBlock.register(PylonKeys.BRONZE_SILO, Material.ORANGE_TERRACOTTA, Silo.class);
        RebarBlock.register(PylonKeys.STEEL_SILO, Material.GRAY_TERRACOTTA, Silo.class);
        RebarBlock.register(PylonKeys.PALLADIUM_SILO, Material.BLUE_TERRACOTTA, Silo.class);
        RebarBlock.register(PylonKeys.SILO_CONVERTER, Material.STRIPPED_OAK_LOG, SiloConverter.class);
        RebarBlock.register(PylonKeys.LISELETTE_COLLECTOR, Material.STRUCTURE_VOID, LiseletteCollector.class);
        RebarBlock.register(PylonKeys.EXPERIENCE_DRAIN, Material.BLACKSTONE_SLAB, ExperienceDrain.class);
        RebarBlock.register(PylonKeys.EXPERIENCE_FOUNTAIN, Material.END_STONE, ExperienceFountain.class);
        RebarBlock.register(PylonKeys.EXPERIENCE_FOUNTAIN_SPOUT, Material.END_ROD, RebarBlock.class);
        RebarBlock.register(PylonKeys.HYDRAULIC_EXPERIENCE_BOTTLER, Material.BREWING_STAND, FluidExperienceBottler.class);
        RebarBlock.register(PylonKeys.DIESEL_EXPERIENCE_BOTTLER, Material.BREWING_STAND, FluidExperienceBottler.class);
        // RebarBlock.register(PylonKeys.SLEEPING_BAG, Material.RED_BED, SleepingBag.class);
    }
}
